version: '3.9'

services:
  frontend:
    image: dwanderingsoul/dream-frontend:${FRONTEND_TAG}
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - vacation-net

  backend:
    image: dwanderingsoul/dream-backend:${BACKEND_TAG}
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db
    networks:
      - vacation-net

  db:
    image: postgres:14
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${DB_PORT}
    networks:
      - vacation-net

volumes:
  pgdata:

networks:
  vacation-net:
    driver: bridge
