version: '3.9'
services:
  frontend:
    image: dwanderingsoul/dream-frontend:${FRONTEND_TAG}
    ports:
      - "80:80"  # Changed from "3000:80" to "80:80" to match security group
    depends_on:
      - backend
    networks:
      - vacation-net
  backend:
    image: dwanderingsoul/dream-backend:${BACKEND_TAG}
    ports:
      - "3001:5000"  # Changed from "5000:5000" to "3001:5000" to match security group
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db
    networks:
      - vacation-net
  db:
    image: postgres:14
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${DB_PORT}
    networks:
      - vacation-net
volumes:
  pgdata:
networks:
  vacation-net:
    driver: bridge
