name: Deploy Dream Vacation App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      
      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      
      - name: Add EC2 to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      # Copy docker-compose file and code to EC2
      - name: Copy docker-compose and code to EC2
        run: |
          scp -o StrictHostKeyChecking=no docker-compose.yml ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/
          scp -o StrictHostKeyChecking=no -r ./backend ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/
          scp -o StrictHostKeyChecking=no -r ./frontend ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/

      # Run Docker Compose on EC2
      - name: Deploy on EC2 with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            set -eux
            cd /home/ubuntu
            docker compose pull
            docker compose up -d --build
            docker ps
          EOF
