name: Deploy Dream Vacation App

on:
  workflow_dispatch:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Sync files to EC2
      - name: Sync files to EC2 with rsync
        uses: burnett01/rsync-deployments@5.0
        with:
          switches: -avz --delete 
          path: ./
          remote_path: /home/ubuntu/dream-vacation
          remote_host: ${{ secrets.EC2_PUBLIC_IP }}
          remote_user: ubuntu
          remote_key: ${{ secrets.EC2_SSH_KEY }}
      

      # Deploy app on EC2
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt update && sudo apt install -y jq
            cd /home/ubuntu/dream-vacation
        
            FRONTEND_SHA=$(curl -s "https://hub.docker.com/v2/repositories/aiyus/dream-frontend/tags?page_size=1&page=1&ordering=last_updated" | jq -r '.results[0].name')
            BACKEND_SHA=$(curl -s "https://hub.docker.com/v2/repositories/aiyus/dream-backend/tags?page_size=1&page=1&ordering=last_updated" | jq -r '.results[0].name')

            cat <<EOF > .env
              FRONTEND_TAG=${FRONTEND_SHA}
              BACKEND_TAG=${BACKEND_SHA}
              DB_PORT=${{ secrets.DB_PORT }}
              POSTGRES_DB=${{ secrets.POSTGRES_DB }}
              POSTGRES_USER=${{ secrets.POSTGRES_USER }}
              POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            EOF

    
            docker compose pull
            docker compose up -d --remove-orphans
