name: Frontend CI/CD

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Run tests
        run: npm test

  build-push:
    needs: lint-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/dream-frontend:${{ github.sha }} .
      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/dream-frontend:${{ github.sha }}
